const ActionTypes = {
  ADD_PLACE: 'ADD_PLACE',
  SET_PLACES: 'SET_PLACES',
  DELETE_PLACE: 'DELETE_PLACE',
  UI_START_LOADING: 'UI_START_LOADING',
  UI_STOP_LOADING: 'UI_STOP_LOADING'
};

export default ActionTypes;